version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      mynetwork:

  redis:
    image: redis:latest
    volumes:
      - redis_data:/root/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${DB_PASSWORD}
      REDIS_PORT: 6379
      REDIS_DATABASES: 3
    networks:
      mynetwork:

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      mynetwork:

volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork: